[project]
name = "ticktacktoe-pygame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "pygbag>=0.9.2",
    "pyinstaller>=6.16.0",
]